### ISSUE TITLE
Application Build Error

### ISSUE THREAD

**Issue by christopherholmes** [chfritz/meteor-ros#6]
Hi Christian, 

I wonder if this package has been used on Meteor version 1.8.0.1? 

I'm receiving the same error output on releases, 0.1.1 and 0.1.0.

Have successfully added the package to my app but just running into an error with the 'split' property. Could offer any assistance at all, error output below : -

=> Started proxy.                             
=> Started MongoDB.                           
I20190103-14:28:41.593(0)? 9                  
=> Started your app.

=> App running at: http://localhost:3000/
W20190103-14:29:16.635(0)? (STDERR) /home/chris/.meteor/packages/meteor-tool/.1.8.0_1.7301r7.323ky++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190103-14:29:16.636(0)? (STDERR) 						throw(ex);
W20190103-14:29:16.636(0)? (STDERR) 						^
W20190103-14:29:16.636(0)? (STDERR) 
W20190103-14:29:16.636(0)? (STDERR) TypeError: Cannot read property 'split' of undefined
W20190103-14:29:16.636(0)? (STDERR)     at Object.<anonymous> (/home/chris/.meteor/packages/chfritz_ros/.0.1.1.16mbcw8.kez3++os+web.browser+web.cordova/npm/node_modules/rosnodejs/utils/message_utils.js:30:28)
W20190103-14:29:16.636(0)? (STDERR)     at Module._compile (module.js:652:30)
W20190103-14:29:16.636(0)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20190103-14:29:16.637(0)? (STDERR)     at Module.load (module.js:565:32)
W20190103-14:29:16.637(0)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20190103-14:29:16.637(0)? (STDERR)     at Function.Module._load (module.js:497:3)
W20190103-14:29:16.637(0)? (STDERR)     at Module.require (module.js:596:17)
W20190103-14:29:16.637(0)? (STDERR)     at require (internal/module.js:11:18)
W20190103-14:29:16.637(0)? (STDERR)     at Object.<anonymous> (/home/chris/.meteor/packages/chfritz_ros/.0.1.1.16mbcw8.kez3++os+web.browser+web.cordova/npm/node_modules/rosnodejs/index.js:23:18)
W20190103-14:29:16.637(0)? (STDERR)     at Module._compile (module.js:652:30)
W20190103-14:29:16.637(0)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20190103-14:29:16.637(0)? (STDERR)     at Module.load (module.js:565:32)
W20190103-14:29:16.637(0)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20190103-14:29:16.637(0)? (STDERR)     at Function.Module._load (module.js:497:3)
W20190103-14:29:16.637(0)? (STDERR)     at Module.require (module.js:596:17)
W20190103-14:29:16.637(0)? (STDERR)     at require (internal/module.js:11:18)
=> Exited with code: 1

Any help would be much appreciated. 

Thanks, 

Chris.

**Comment by chfritz** [comment]
I haven't tried on meteor 1.8 yet, but the error is a well known issue: you have probably not sourced your ROS environment before starting meteor. The `split` that is failing is on the content of an environment variable that is set by ROS's `setup.[bash|sh|zsh]`. Can you try again after sourcing that file in the terminal where you start meteor? (usually `source /opt/ros/kinetic/setup.bash`) Please let me know if that fixes it.

**Comment by christopherholmes** [comment]
Ah, that's great, thank you, that works. I hadn't sourced the ROS environment into the same terminal session as the Meteor app. 

I'm just running into an error, when calling ROS inside my (/server/main.js with the line : -
```
const ros = ROS();
```

I seem to be getting an unresolved promise. It looks to be when trying to create the new RosNode, I'm unsure if Meteor is able to connect to ROS Master successfully, I have confirmed local host and the port (http://localhost:11311) , I have put the exit output below. 

I wonder if you have any ideas on this at all? 

Thanks again, much appreciated. 

```
=> Started proxy.                             
=> Started MongoDB.                           
I20190107-09:17:21.486(0)? [INFO] 2019-01-07 09:17:21.475+0000: Connecting to ROS Master at http://localhost:11311
W20190107-09:17:21.564(0)? (STDERR) (node:13133) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'unshift' of undefined
W20190107-09:17:21.565(0)? (STDERR)     at /home/chris/.meteor/packages/chfritz_ros/.0.1.1.16mbcw8.kez3++os+web.browser+web.cordova/npm/node_modules/rosnodejs/index.js:217:15
W20190107-09:17:21.566(0)? (STDERR)     at Array.forEach (<anonymous>)
W20190107-09:17:21.567(0)? (STDERR)     at Object._useMessages (/home/chris/.meteor/packages/chfritz_ros/.0.1.1.16mbcw8.kez3++os+web.browser+web.cordova/npm/node_modules/rosnodejs/index.js:213:7)
W20190107-09:17:21.567(0)? (STDERR)     at Promise (/home/chris/.meteor/packages/chfritz_ros/.0.1.1.16mbcw8.kez3++os+web.browser+web.cordova/npm/node_modules/rosnodejs/index.js:196:12)
W20190107-09:17:21.568(0)? (STDERR)     at new Promise (<anonymous>)
W20190107-09:17:21.569(0)? (STDERR)     at Object.use (/home/chris/.meteor/packages/chfritz_ros/.0.1.1.16mbcw8.kez3++os+web.browser+web.cordova/npm/node_modules/rosnodejs/index.js:195:12)
W20190107-09:17:21.569(0)? (STDERR)     at Promise (/home/chris/.meteor/packages/chfritz_ros/.0.1.1.16mbcw8.kez3++os+web.browser+web.cordova/npm/node_modules/rosnodejs/index.js:136:12)
W20190107-09:17:21.570(0)? (STDERR)     at new Promise (<anonymous>)
W20190107-09:17:21.571(0)? (STDERR)     at Object.initNode (/home/chris/.meteor/packages/chfritz_ros/.0.1.1.16mbcw8.kez3++os+web.browser+web.cordova/npm/node_modules/rosnodejs/index.js:135:12)
W20190107-09:17:21.571(0)? (STDERR)     at packages/chfritz:ros/server/main.js:20:13
W20190107-09:17:21.572(0)? (STDERR)     at packages/meteor.js:376:21
W20190107-09:17:21.573(0)? (STDERR)     at new ROSHandler (packages/chfritz:ros/server/main.js:19:21)
W20190107-09:17:21.573(0)? (STDERR)     at ROS (packages/chfritz:ros/server/main.js:139:10)
W20190107-09:17:21.574(0)? (STDERR)     at main.js (server/main.js:11:13)
W20190107-09:17:21.574(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190107-09:17:21.575(0)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190107-09:17:21.576(0)? (STDERR) (node:13133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
W20190107-09:17:21.576(0)? (STDERR) (node:13133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chfritz** [comment]
hm, that's strange. It's possible that this is due to Meteor 1.8, I haven't tried that. But this works fine on meteor 1.6. I'm assuming you are on kinetic (ubuntu 16.04)?
